name: little_emmi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running flutter pub upgrade --major-versions. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run flutter pub outdated.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  webview_flutter: ^4.13.1
  flutter_tts: ^3.8.3
  image_picker: ^1.1.2
  flutter_blue_plus: ^1.34.5
  flutter_libserialport: ^0.6.0  # Fixes SerialPort errors
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  model_viewer_plus: ^1.7.0
  provider: ^6.1.5+1
  connectivity_plus: ^6.1.0
  uuid: ^4.5.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0 # Add this line
  device_info_plus: ^10.1.0
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  font_awesome_flutter: ^10.10.0
  percent_indicator: ^4.2.5
  intl: ^0.18.0
  url_launcher: ^6.3.2
  archive: ^3.6.1
  flutter_inappwebview: ^6.1.5
  sensors_plus: ^7.0.0
  shared_preferences: ^2.2.3
  dotted_border: ^2.0.0
  process_run: 1.2.4
  path: ^1.9.0
  flutter_code_editor: ^0.3.1 # Check pub.dev for the latest version
  flutter_highlight: ^0.7.0  # Required by the code editor for syntax highlighting
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  # Required for handling camera/location permissions
  permission_handler: ^12.0.1
  # Math library for 3D vector calculations
  vector_math: ^2.1.4
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  webview_windows: ^0.4.0
  google_generative_ai: ^0.4.7
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  camera_windows: ^0.2.1
  camera: ^0.10.5+9

  highlight: any
  camera_macos: ^0.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/qubiq_logo.png"
  min_sdk_android: 21

  # âœ… ENABLE MACOS SUPPORT
  macos:
    generate: true
    image_path: "assets/images/qubiq_logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - ./lib/Resources/little_emmi.svg
    - ./lib/Resources/BlocksStructure/blueCmd.svg
    - ./lib/Resources/MovementIcons/Foward.svg
    - ./lib/Resources/MovementIcons/Back.svg
    - ./lib/Resources/MovementIcons/Up.svg
    - ./lib/Resources/MovementIcons/Down.svg
    - lib/Resources/loopIcons/repeat.png
    - lib/Resources/loopIcons/repeatblock.png
    - ./lib/Resources/loopIcons/Repeat.svg
    - ./lib/Resources/loopIcons/repeatsvg.svg
    - assets/images/qubiq_logo.png
    - assets/curriculum.json
    - assets/mobilenet_feature.tflite
    - assets/images/chatai.png
    - assets/images/
    - assets/web.zip
    - assets/www/
    - assets/www/blocks/
    - assets/www/lib/
    - assets/www/lib/codemirror/
    - assets/www/lib/skulpt/
    - assets/www/lib/blockly/
    - assets/www/index_MIT.html
    - assets/www/vite.svg
    - assets/www/assets/index-JKwT_vHL.css
    - assets/www/assets/index-xPsAilHw.js
    - assets/web/dist/
    - assets/web/dist/assets/
    - assets/web/dist/index.html
    - assets/web/dist/vite.svg
    - assets/web/dist/assets/index-DDzBPqJa.css
    - assets/web/dist/assets/index-BbfzEzEM.js
    - assets/excel_web/dist/
    - assets/excel_web/dist/assets/
    - assets/excel_web/dist/index.html
    - assets/excel_web/dist/vite.svg
    - assets/excel_web/dist/assets/index-uY9H4Hhg.css
    - assets/excel_web/dist/assets/index-Ee9A-V15.js
    - assets/word_web/word/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

